# Generated by Django 4.1.4 on 2022-12-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
