# Generated by Django 4.1.4 on 2022-12-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0003_cloth_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloth',
            options={'permissions': [('special_status', 'Can view all cloths')]},
        ),
    ]
